version: '3.8'

services:
  share-price-server:
    build: .
    command: python run_share_price.py
    environment:
      - BB_FINANCE_API_KEY=${BB_FINANCE_API_KEY}
      - BB_FINANCE_BASE_URL=${BB_FINANCE_BASE_URL}
      - BB_FINANCE_CHART_URL=${BB_FINANCE_CHART_URL}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    ports:
      - "8001:8000"
    volumes:
      - ./.env:/app/.env:ro
    restart: unless-stopped

  pinecone-server:
    build: .
    command: python run_pinecone.py
    environment:
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_DEFAULT_INDEX=${PINECONE_DEFAULT_INDEX}
      - PINECONE_DEFAULT_DIMENSION=${PINECONE_DEFAULT_DIMENSION}
      - PINECONE_DEFAULT_METRIC=${PINECONE_DEFAULT_METRIC}
      - PINECONE_CLOUD=${PINECONE_CLOUD}
      - PINECONE_REGION=${PINECONE_REGION}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    ports:
      - "8002:8000"
    volumes:
      - ./.env:/app/.env:ro
    restart: unless-stopped
